directories:
  output: release
  buildResources: build
appId: com.sakar.guard
productName: Guard Controls
files:
  - filter:
      - dist/**/*
      - electron.mjs
      - preload.js
      - package.json
extraFiles:
  - from: resources/app/main
    to: app/main
asar: false
linux:
  target:
    - AppImage
  category: Utility
electronVersion: 38.1.2
